development:
  app_id: L6SLBxrQtNVjvdO8TCaYH7rpMHStR832rJoTloW0
  master_key: f1zN9gg2YNi1CYGn1rOC7shpifEkNHOUIrQ1jcbN

test:
  app_id: L6SLBxrQtNVjvdO8TCaYH7rpMHStR832rJoTloW0
  master_key: f1zN9gg2YNi1CYGn1rOC7shpifEkNHOUIrQ1jcbN

production:
  app_id: L6SLBxrQtNVjvdO8TCaYH7rpMHStR832rJoTloW0
  master_key: f1zN9gg2YNi1CYGn1rOC7shpifEkNHOUIrQ1jcbN